//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace Newtonsoft.Json.Tests.Dot42
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawable
        {
            
            public const int bunny_pancake = 0x7f020000;
        }
        
        public sealed class Layout
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Id
        {
        }
    }
}
